services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - vincular-net

volumes:
  evolution_instances:

networks:
  vincular-net:
    external: true
    name: vincular-net